// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using VolvoCash.Data.MainContext;

namespace VolvoCash.DistributedServices.MainContext.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20201125063422_UpdateCurrencyToBankAccountRequired")]
    partial class UpdateCurrencyToBankAccountRequired
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.BankAccountAgg.BankAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("ArchiveAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("BankAccountTypeId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("BankId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("CCI")
                        .HasColumnType("NVARCHAR2(40)")
                        .HasMaxLength(40);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("DealerId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("BankAccountTypeId");

                    b.HasIndex("BankId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("DealerId");

                    b.ToTable("BankAccounts");
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.BankAccountAgg.BankAccountType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ArchiveAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("BankAccountTypes");
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.BankAgg.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbreviation")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("ArchiveAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TPCode")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.BankAgg.BankBankAccountType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BankAccountTypeId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("BankId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Equivalence")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("BankAccountTypeId");

                    b.HasIndex("BankId");

                    b.ToTable("BankBankAccountTypes");
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.BankAgg.BankCurrency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BankId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Equivalence")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("CurrencyId");

                    b.ToTable("BankCurrencies");
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.BankAgg.BankDocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BankId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Equivalence")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("DocumentTypeId");

                    b.ToTable("BankDocumentTypes");
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.BatchAgg.Batch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BusinessAreaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("CardId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("CardTypeId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ClientId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ContactId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DealerCode")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DealerName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("ExpiresAtExtent")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("LineContent")
                        .HasColumnType("NCLOB")
                        .HasMaxLength(4000);

                    b.Property<int?>("RechargeTypeId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TPChasis")
                        .HasColumnType("NVARCHAR2(20)")
                        .HasMaxLength(20);

                    b.Property<string>("TPContractBatchNumber")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("TPContractDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("TPContractNumber")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TPInvoiceCode")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("TPInvoiceDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("TPReason")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessAreaId");

                    b.HasIndex("CardId");

                    b.HasIndex("CardTypeId");

                    b.HasIndex("ClientId");

                    b.HasIndex("ContactId");

                    b.HasIndex("RechargeTypeId");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.BatchAgg.BatchError", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("NVARCHAR2(300)")
                        .HasMaxLength(300);

                    b.Property<string>("FileName")
                        .HasColumnType("NVARCHAR2(300)")
                        .HasMaxLength(300);

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("LineContent")
                        .HasColumnType("NCLOB")
                        .HasMaxLength(4000);

                    b.Property<int>("RowIndex")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("BatchErrors");
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.BatchAgg.BatchMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BatchId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("MovementId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("MovementId");

                    b.ToTable("BatchMovements");
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.BusinessAreaAgg.BusinessArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ArchiveAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TPCode")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("BusinessAreas");
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.CardAgg.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ArchiveAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("CardTypeId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(20)")
                        .HasMaxLength(20);

                    b.Property<int>("ContactId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TPCode")
                        .HasColumnType("NVARCHAR2(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("CardTypeId");

                    b.HasIndex("ContactId");

                    b.HasIndex("CurrencyId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.CardAgg.CardBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BatchId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("CardId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("CardId");

                    b.ToTable("CardBatches");
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.CardAgg.CardType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ArchiveAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(10)")
                        .HasMaxLength(10);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(20)")
                        .HasMaxLength(20);

                    b.Property<string>("ImageUrl")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TPCode")
                        .HasColumnType("NVARCHAR2(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Term")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.ToTable("CardTypes");
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.CardAgg.Charge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CardId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("CashierId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ChargeType")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("NVARCHAR2(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("HasBeenRefunded")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("LiquidationId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("OperationCode")
                        .HasColumnType("NVARCHAR2(20)")
                        .HasMaxLength(20);

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("CashierId");

                    b.HasIndex("LiquidationId");

                    b.ToTable("Charges");
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.CardAgg.Movement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CardId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("ChargeId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(200)")
                        .HasMaxLength(200);

                    b.Property<string>("DisplayName")
                        .HasColumnType("NVARCHAR2(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("TransferId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Type")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("ChargeId");

                    b.HasIndex("TransferId");

                    b.ToTable("Movements");
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.CardAgg.Transfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(100)")
                        .HasMaxLength(100);

                    b.Property<int>("DestinyCardId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("NVARCHAR2(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ImageUrl")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("OperationCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(20)")
                        .HasMaxLength(20);

                    b.Property<int>("OriginCardId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("DestinyCardId");

                    b.HasIndex("OriginCardId");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.ClientAgg.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("NVARCHAR2(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("ArchiveAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Email")
                        .HasColumnType("NVARCHAR2(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Phone")
                        .HasColumnType("NVARCHAR2(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(11)")
                        .HasMaxLength(11);

                    b.Property<int?>("SectorId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TPCode")
                        .HasColumnType("NVARCHAR2(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.ContactAgg.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ArchiveAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("ClientId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("ContactParentId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("DocumentTypeId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Email")
                        .HasColumnType("NVARCHAR2(100)")
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(20)")
                        .HasMaxLength(20);

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Type")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ContactParentId");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.CurrencyAgg.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbreviation")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("ArchiveAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Symbol")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TPCode")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.DealerAgg.Dealer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("NVARCHAR2(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("ArchiveAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("ContactName")
                        .HasColumnType("NVARCHAR2(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("MaxCashiers")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Phone")
                        .HasColumnType("NVARCHAR2(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(11)")
                        .HasMaxLength(11);

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TPCode")
                        .HasColumnType("NVARCHAR2(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Type")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Zone")
                        .HasColumnType("NVARCHAR2(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Dealers");
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.DocumentTypeAgg.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbreviation")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("ArchiveAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(100)")
                        .HasMaxLength(100);

                    b.Property<string>("SUNATCode")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TPCode")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("DocumentTypes");
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.LiquidationAgg.Liquidation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("DealerId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("LiquidationStatus")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("DealerId");

                    b.ToTable("Liquidations");
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.RechargeTypeAgg.RechargeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ArchiveAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TPCode")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("RechargeTypes");
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.SMSCodeAgg.SMSCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Code")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("DateTimeUsed")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("ItWasAlreadyUsed")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("SMSCodes");
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.SectorAgg.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ArchiveAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TPCode")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Sectors");
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.UserAgg.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ArchiveAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("DealerId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(100)")
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(100)")
                        .HasMaxLength(100);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(400)")
                        .HasMaxLength(400);

                    b.Property<string>("Phone")
                        .HasColumnType("NVARCHAR2(20)")
                        .HasMaxLength(20);

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("DealerId");

                    b.HasIndex("UserId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.UserAgg.Cashier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ArchiveAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("DealerId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(50)")
                        .HasMaxLength(50);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Imei")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(100)")
                        .HasMaxLength(100);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(400)")
                        .HasMaxLength(400);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(20)")
                        .HasMaxLength(20);

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TPCode")
                        .HasColumnType("NVARCHAR2(100)")
                        .HasMaxLength(100);

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("DealerId");

                    b.HasIndex("UserId");

                    b.ToTable("Cashiers");
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.UserAgg.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("PushDeviceToken")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.UserAgg.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Type")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.BankAccountAgg.BankAccount", b =>
                {
                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.BankAccountAgg.BankAccountType", "BankAccountType")
                        .WithMany()
                        .HasForeignKey("BankAccountTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.BankAgg.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.CurrencyAgg.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.DealerAgg.Dealer", "Dealer")
                        .WithMany("BankAccounts")
                        .HasForeignKey("DealerId");
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.BankAgg.BankBankAccountType", b =>
                {
                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.BankAccountAgg.BankAccountType", "BankAccountType")
                        .WithMany("BankBankAccountTypes")
                        .HasForeignKey("BankAccountTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.BankAgg.Bank", "Bank")
                        .WithMany("BankBankAccountTypes")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.BankAgg.BankCurrency", b =>
                {
                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.BankAgg.Bank", "Bank")
                        .WithMany("BankCurrencies")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.CurrencyAgg.Currency", "Currency")
                        .WithMany("BankCurrencies")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.BankAgg.BankDocumentType", b =>
                {
                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.BankAgg.Bank", "Bank")
                        .WithMany("BankDocumentTypes")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.DocumentTypeAgg.DocumentType", "DocumentType")
                        .WithMany("BankDocumentTypes")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.BatchAgg.Batch", b =>
                {
                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.BusinessAreaAgg.BusinessArea", "BusinessArea")
                        .WithMany()
                        .HasForeignKey("BusinessAreaId");

                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.CardAgg.Card", "Card")
                        .WithMany("Batches")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.CardAgg.CardType", "CardType")
                        .WithMany()
                        .HasForeignKey("CardTypeId");

                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.ClientAgg.Client", "Client")
                        .WithMany("Batches")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.ContactAgg.Contact", "Contact")
                        .WithMany("Batches")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.RechargeTypeAgg.RechargeType", "RechargeType")
                        .WithMany()
                        .HasForeignKey("RechargeTypeId");

                    b.OwnsOne("VolvoCash.Domain.MainContext.Aggregates.CardAgg.Money", "Amount", b1 =>
                        {
                            b1.Property<int>("BatchId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("NUMBER(10)")
                                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("CurrencyId")
                                .HasColumnType("NUMBER(10)");

                            b1.Property<double>("Value")
                                .HasColumnType("BINARY_DOUBLE");

                            b1.HasKey("BatchId");

                            b1.HasIndex("CurrencyId");

                            b1.ToTable("Batches");

                            b1.WithOwner()
                                .HasForeignKey("BatchId");

                            b1.HasOne("VolvoCash.Domain.MainContext.Aggregates.CurrencyAgg.Currency", "Currency")
                                .WithMany()
                                .HasForeignKey("CurrencyId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();
                        });

                    b.OwnsOne("VolvoCash.Domain.MainContext.Aggregates.CardAgg.Money", "Balance", b1 =>
                        {
                            b1.Property<int>("BatchId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("NUMBER(10)")
                                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("CurrencyId")
                                .HasColumnType("NUMBER(10)");

                            b1.Property<double>("Value")
                                .HasColumnType("BINARY_DOUBLE");

                            b1.HasKey("BatchId");

                            b1.HasIndex("CurrencyId");

                            b1.ToTable("Batches");

                            b1.WithOwner()
                                .HasForeignKey("BatchId");

                            b1.HasOne("VolvoCash.Domain.MainContext.Aggregates.CurrencyAgg.Currency", "Currency")
                                .WithMany()
                                .HasForeignKey("CurrencyId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();
                        });
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.BatchAgg.BatchMovement", b =>
                {
                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.BatchAgg.Batch", "Batch")
                        .WithMany("BatchMovements")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.CardAgg.Movement", "Movement")
                        .WithMany("BatchMovements")
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("VolvoCash.Domain.MainContext.Aggregates.CardAgg.Money", "Amount", b1 =>
                        {
                            b1.Property<int>("BatchMovementId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("NUMBER(10)")
                                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("CurrencyId")
                                .HasColumnType("NUMBER(10)");

                            b1.Property<double>("Value")
                                .HasColumnType("BINARY_DOUBLE");

                            b1.HasKey("BatchMovementId");

                            b1.HasIndex("CurrencyId");

                            b1.ToTable("BatchMovements");

                            b1.WithOwner()
                                .HasForeignKey("BatchMovementId");

                            b1.HasOne("VolvoCash.Domain.MainContext.Aggregates.CurrencyAgg.Currency", "Currency")
                                .WithMany()
                                .HasForeignKey("CurrencyId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();
                        });
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.CardAgg.Card", b =>
                {
                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.CardAgg.CardType", "CardType")
                        .WithMany("Cards")
                        .HasForeignKey("CardTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.ContactAgg.Contact", "Contact")
                        .WithMany("Cards")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.CurrencyAgg.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId");

                    b.OwnsOne("VolvoCash.Domain.MainContext.Aggregates.CardAgg.Money", "Balance", b1 =>
                        {
                            b1.Property<int>("CardId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("NUMBER(10)")
                                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("CurrencyId")
                                .HasColumnType("NUMBER(10)");

                            b1.Property<double>("Value")
                                .HasColumnType("BINARY_DOUBLE");

                            b1.HasKey("CardId");

                            b1.HasIndex("CurrencyId");

                            b1.ToTable("Cards");

                            b1.WithOwner()
                                .HasForeignKey("CardId");

                            b1.HasOne("VolvoCash.Domain.MainContext.Aggregates.CurrencyAgg.Currency", "Currency")
                                .WithMany()
                                .HasForeignKey("CurrencyId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();
                        });
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.CardAgg.CardBatch", b =>
                {
                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.BatchAgg.Batch", "Batch")
                        .WithMany("CardBatches")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.CardAgg.Card", "Card")
                        .WithMany("CardBatches")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("VolvoCash.Domain.MainContext.Aggregates.CardAgg.Money", "Balance", b1 =>
                        {
                            b1.Property<int>("CardBatchId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("NUMBER(10)")
                                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("CurrencyId")
                                .HasColumnType("NUMBER(10)");

                            b1.Property<double>("Value")
                                .HasColumnType("BINARY_DOUBLE");

                            b1.HasKey("CardBatchId");

                            b1.HasIndex("CurrencyId");

                            b1.ToTable("CardBatches");

                            b1.WithOwner()
                                .HasForeignKey("CardBatchId");

                            b1.HasOne("VolvoCash.Domain.MainContext.Aggregates.CurrencyAgg.Currency", "Currency")
                                .WithMany()
                                .HasForeignKey("CurrencyId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();
                        });
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.CardAgg.CardType", b =>
                {
                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.CurrencyAgg.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId");
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.CardAgg.Charge", b =>
                {
                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.CardAgg.Card", "Card")
                        .WithMany("Charges")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.UserAgg.Cashier", "Cashier")
                        .WithMany("Charges")
                        .HasForeignKey("CashierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.LiquidationAgg.Liquidation", "Liquidation")
                        .WithMany("Charges")
                        .HasForeignKey("LiquidationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("VolvoCash.Domain.MainContext.Aggregates.CardAgg.Money", "Amount", b1 =>
                        {
                            b1.Property<int>("ChargeId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("NUMBER(10)")
                                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("CurrencyId")
                                .HasColumnType("NUMBER(10)");

                            b1.Property<double>("Value")
                                .HasColumnType("BINARY_DOUBLE");

                            b1.HasKey("ChargeId");

                            b1.HasIndex("CurrencyId");

                            b1.ToTable("Charges");

                            b1.WithOwner()
                                .HasForeignKey("ChargeId");

                            b1.HasOne("VolvoCash.Domain.MainContext.Aggregates.CurrencyAgg.Currency", "Currency")
                                .WithMany()
                                .HasForeignKey("CurrencyId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();
                        });
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.CardAgg.Movement", b =>
                {
                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.CardAgg.Card", "Card")
                        .WithMany("Movements")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.CardAgg.Charge", "Charge")
                        .WithMany("Movements")
                        .HasForeignKey("ChargeId");

                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.CardAgg.Transfer", "Transfer")
                        .WithMany("Movements")
                        .HasForeignKey("TransferId");

                    b.OwnsOne("VolvoCash.Domain.MainContext.Aggregates.CardAgg.Money", "Amount", b1 =>
                        {
                            b1.Property<int>("MovementId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("NUMBER(10)")
                                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("CurrencyId")
                                .HasColumnType("NUMBER(10)");

                            b1.Property<double>("Value")
                                .HasColumnType("BINARY_DOUBLE");

                            b1.HasKey("MovementId");

                            b1.HasIndex("CurrencyId");

                            b1.ToTable("Movements");

                            b1.HasOne("VolvoCash.Domain.MainContext.Aggregates.CurrencyAgg.Currency", "Currency")
                                .WithMany()
                                .HasForeignKey("CurrencyId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("MovementId");
                        });
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.CardAgg.Transfer", b =>
                {
                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.CardAgg.Card", "DestinyCard")
                        .WithMany("DestinyTransfers")
                        .HasForeignKey("DestinyCardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.CardAgg.Card", "OriginCard")
                        .WithMany("OriginTransfers")
                        .HasForeignKey("OriginCardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("VolvoCash.Domain.MainContext.Aggregates.CardAgg.Money", "Amount", b1 =>
                        {
                            b1.Property<int>("TransferId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("NUMBER(10)")
                                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("CurrencyId")
                                .HasColumnType("NUMBER(10)");

                            b1.Property<double>("Value")
                                .HasColumnType("BINARY_DOUBLE");

                            b1.HasKey("TransferId");

                            b1.HasIndex("CurrencyId");

                            b1.ToTable("Transfers");

                            b1.HasOne("VolvoCash.Domain.MainContext.Aggregates.CurrencyAgg.Currency", "Currency")
                                .WithMany()
                                .HasForeignKey("CurrencyId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("TransferId");
                        });
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.ClientAgg.Client", b =>
                {
                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.SectorAgg.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId");
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.ContactAgg.Contact", b =>
                {
                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.ClientAgg.Client", "Client")
                        .WithMany("Contacts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.ContactAgg.Contact", "ContactParent")
                        .WithMany("ContactChildren")
                        .HasForeignKey("ContactParentId");

                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.DocumentTypeAgg.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId");

                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.UserAgg.User", "User")
                        .WithMany("Contacts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.LiquidationAgg.Liquidation", b =>
                {
                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.DealerAgg.Dealer", "Dealer")
                        .WithMany()
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("VolvoCash.Domain.MainContext.Aggregates.CardAgg.Money", "Amount", b1 =>
                        {
                            b1.Property<int>("LiquidationId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("NUMBER(10)")
                                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("CurrencyId")
                                .HasColumnType("NUMBER(10)");

                            b1.Property<double>("Value")
                                .HasColumnType("BINARY_DOUBLE");

                            b1.HasKey("LiquidationId");

                            b1.HasIndex("CurrencyId");

                            b1.ToTable("Liquidations");

                            b1.HasOne("VolvoCash.Domain.MainContext.Aggregates.CurrencyAgg.Currency", "Currency")
                                .WithMany()
                                .HasForeignKey("CurrencyId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("LiquidationId");
                        });
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.UserAgg.Admin", b =>
                {
                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.DealerAgg.Dealer", "Dealer")
                        .WithMany()
                        .HasForeignKey("DealerId");

                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.UserAgg.User", "User")
                        .WithMany("Admins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.UserAgg.Cashier", b =>
                {
                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.DealerAgg.Dealer", "Dealer")
                        .WithMany("Cashiers")
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.UserAgg.User", "User")
                        .WithMany("Cashiers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VolvoCash.Domain.MainContext.Aggregates.UserAgg.Session", b =>
                {
                    b.HasOne("VolvoCash.Domain.MainContext.Aggregates.UserAgg.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
